### ISSUE TITLE
Trouble setting up iptables rule for CS TeamServer.

### ISSUE THREAD

**Issue by volt72** [killswitch-GUI/SMS-LogAlert#2]
Hello let me start by thanking you for this great solution and if you would be so kind to help me as i have ran into a problem using this script, I would really appreciate it. The problem i am having is creating the iptables rule to log every new beacon from the CS teamserver, I have never done this before and from what i have read i must create a rule so that iptables will output the beacons to /var/log/iptables.log, If you would be so kind to share with me the steps you have done to do this you would save me a lot of trouble, Thanks.

**Comment by killswitch-GUI** [comment]
@volt72 Let me send you over how I did this! Currently busy with EmPyre but I do have the rules and Aggressor script I built laying arround.

**Comment by volt72** [comment]
Yes please that would be very appreciated and again i thank you for all of your hard work on this project, i must say it is very clever to log the iptables using a set rule instead of the other solutions i have seen. You can contact me at Volt72@aol.com

**Comment by volt72** [comment]
Created my own thanks.
